//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandsGen.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MouseCommandBase", Namespace="http://schemas.datacontract.org/2004/07/CommandsHandler.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CommandsGen.ServiceReference.StopCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CommandsGen.ServiceReference.MouseMoveCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CommandsGen.ServiceReference.WheelCommand))]
    public partial class MouseCommandBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandName {
            get {
                return this.CommandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandNameField, value) != true)) {
                    this.CommandNameField = value;
                    this.RaisePropertyChanged("CommandName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StopCommand", Namespace="http://schemas.datacontract.org/2004/07/CommandsHandler.Model")]
    [System.SerializableAttribute()]
    public partial class StopCommand : CommandsGen.ServiceReference.MouseCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MouseMoveCommand", Namespace="http://schemas.datacontract.org/2004/07/CommandsHandler.Model")]
    [System.SerializableAttribute()]
    public partial class MouseMoveCommand : CommandsGen.ServiceReference.MouseCommandBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WheelCommand", Namespace="http://schemas.datacontract.org/2004/07/CommandsHandler.Model")]
    [System.SerializableAttribute()]
    public partial class WheelCommand : CommandsGen.ServiceReference.MouseCommandBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IReceiver")]
    public interface IReceiver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiver/SendCommands", ReplyAction="http://tempuri.org/IReceiver/SendCommandsResponse")]
        bool SendCommands(CommandsGen.ServiceReference.MouseCommandBase[] command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiver/SendCommands", ReplyAction="http://tempuri.org/IReceiver/SendCommandsResponse")]
        System.Threading.Tasks.Task<bool> SendCommandsAsync(CommandsGen.ServiceReference.MouseCommandBase[] command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceiverChannel : CommandsGen.ServiceReference.IReceiver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiverClient : System.ServiceModel.ClientBase<CommandsGen.ServiceReference.IReceiver>, CommandsGen.ServiceReference.IReceiver {
        
        public ReceiverClient() {
        }
        
        public ReceiverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendCommands(CommandsGen.ServiceReference.MouseCommandBase[] command) {
            return base.Channel.SendCommands(command);
        }
        
        public System.Threading.Tasks.Task<bool> SendCommandsAsync(CommandsGen.ServiceReference.MouseCommandBase[] command) {
            return base.Channel.SendCommandsAsync(command);
        }
    }
}
